apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-cowv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-cowv
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-cowv
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-cowv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-cowv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-jmdg-tenant/appstudio/dc-metro-map-cowv@sha256:b9df2120e6e1e58b0393614706f8825d1814fd6f42d686d846a4994f7eaf7be7
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
